- name: rich
- name: psutil
- name: Jinja2
- name: pyyaml
# Ansible
- name: ansible_runner
# ansible-core 2.12.6 min version python 3.8
- name: ansible-core
  version: "2.12.6"
- name: pywinrm
# AZURE
- name: azure-identity
- name: azure-mgmt-compute
- name: azure-mgmt-network
# AWS
- name: boto3
# Proxmox
- name: proxmoxer
- name: requests