name: Static Analysis
on:
  pull_request:
    branches:
      - main
      - feature/add-devsecops
    types: [opened, synchronize, reopened]
jobs:
  python-static-analysis:
    name: Python static Analysis
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
            targets: "goad.py,goad"
            severity: "medium"
            confidence: "high"

  iac-static-analysis:
    name: IAC static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kics Scan
        uses: checkmarx/kics-github-action@v2.1.6
        with:
          cloud_provider: aws,azure
          disable_secrets: true
          fail_on: high,medium
          path: 'requirements.yml,requirements_311.yml,playbooks.yml,ansible,template/provider,Dockerfile,.devcontainer/Dockerfile,ad/GOAD/providers,ad/GOAD-Light/providers,ad/GOAD-Mini/providers,ad/MINILAB/providers,ad/NHA/providers,ad/SCCM/providers,ad/GOAD/providers,ad/TEMPLATE/providers'
          output_path: kics-results/
      - name: Display kics results
        run: |
          cat kics-results/results.json